--- #YAML:1.0
name:               Task-Sites-ShlomiFish
version:            0.0204
abstract:           Specifications for modules needed for building www.shlomifish.org , whose sources are publically available, and serve as examples for several technologies.
author:
    - Shlomi Fish <shlomif@iglu.org.il>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    App::XML::DocBook::Builder:  0
    DateTime:             0
    HTML::TokeParser::Simple:  0
    IO::All:              0
    Spork::Shlomify:      0.0200
    String::ShellQuote:   0
    Task::Latemp:         0
    Template::Preprocessor::TTML:  0
    Term::ReadPassword:   0
    Text::VimColor:       0
    XML::Grammar::Fiction:  0
    XML::Grammar::Fortune:  0.0107
    XML::Grammar::Fortune::Synd::App:  0
    XML::Grammar::ProductsSyndication:  0.0302
    XML::Grammar::Screenplay:  0.0501
    XML::LibXML::XPathContext:  0
    XML::LibXSLT:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
