--- #YAML:1.0
name:                Task-Sites-ShlomiFish
version:             0.0202
abstract:            Specifications for modules needed for building www.shlomifish.org , whose sources are publically available, and serve as examples for several technologies.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    App::XML::DocBook::Builder:    0
    DateTime:                      0
    HTML::TokeParser::Simple:      0
    IO::All:                       0
    String::ShellQuote:            0
    Task::Latemp:                  0
    Template::Preprocessor::TTML:  0
    WWW::Google::SiteMap:          0
    XML::Grammar::Fortune:         0.0107
    XML::Grammar::Fortune::Synd::App: 0
    XML::Grammar::ProductsSyndication: 0.0302
    XML::Grammar::Screenplay:      0.0501
    XML::LibXML::XPathContext:     0
    XML::LibXSLT:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Shlomi Fish <shlomif@iglu.org.il>
